version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - echo "Empaquetando Lambda..."
      - cd lambda
      - zip -r ../post_webcase_function.zip .
      - cd ..

artifacts:
  files:
    - post_webcase_function.zip
    - template.yaml
