version: 0.2
phases:
  build:
    commands:
      - echo "Empaquetando las funciones Lambda..."
      - zip -r post_webcase_function.zip . -i 'app.py' 'template.yaml'
      - zip -r post_support_function.zip . -i 'support_app.py' 'template.yaml'
      - zip -r create_case_email_function.zip . -i 'email_app.py' 'template.yaml'
      - echo "Validando la plantilla CloudFormation..."
      - aws cloudformation validate-template --template-body file://template.yaml
  post_build:
    commands:
      - echo "Construcción completa. Subiendo artefactos."
artifacts:
  files:
    - post_webcase_function.zip
    - post_support_function.zip
    - create_case_email_function.zip
    - template.yaml